package com.example.ui.components

object Localization {
    fun get(key: String, lang: String): String {
        val tw = mapOf(
            "app_title" to "🧘 BMI 助理",
            "app_title_dashboard" to "🧘 BMI 助理",
            "app_title_history" to "📊 趨勢歷史歷程",
            "app_title_settings" to "⚙️ 設定與提醒",
            "home" to "首頁",
            "history" to "紀錄",
            "settings" to "設定",
            "trending_and_stats" to "趨勢與統計",
            "history_track" to "測量記錄",
            "export_report" to "匯出報告",
            "all_history" to "所有歷史紀錄",
            "add_record" to "增加紀錄",
            "duplicate_record_title" to "⚠️ 紀錄重複",
            "duplicate_record_desc" to "此日期已存在量測紀錄，是否覆蓋原本的紀錄？",
            "overwrite_btn" to "覆蓋",
            "no_history" to "📌 尚無數據紀錄",
            "no_history_desc" to "點擊首頁右上方『 ＋ 』符號，即可輕鬆快速記錄您的體重與健康，維持完美身型！",
            "delete_confirm_title" to "⚠️ 確定刪除此筆記錄？",
            "delete_confirm_desc" to "您即將刪除體重紀錄。此動作將無法復原。",
            "delete_confirm_btn" to "確定刪除",
            "cancel" to "取消",
            "metric_system" to "📐 單位",
            "metric_system_desc" to "設定您的體重與身高單位，更正後將自動換算歷史紀錄",
            "metric_opt" to "公制 (kg / cm)",
            "imperial_opt" to "英制 (lb / 吋)",
            "physical_metrics" to "👤 個人基本身體指標",
            "target_goals_title" to "🎯 理想健康目標",
            "target_goals_desc" to "設定您的期望體重目標，系統將即時分析對應的預估目標 BMI 指標",
            "target_bmi_label" to "預估目標 BMI：",
            "recommended_standard_weight" to "推薦健康體重（BMI 22.0）：",
            "height_label" to "個人身高",
            "target_weight_label" to "體重",
            "reminder_title" to "⏰ 每日提醒",
            "reminder_desc" to "定時提醒，幫助不漏記任何數據",
            "reminder_hour" to "提醒時辰",
            "reminder_min" to "分鐘",
            "reminder_freq" to "提醒週期間隔頻率",
            "reminder_inactive_desc" to "💡 提醒目前為關閉狀態。建議開啟提醒以收到每日定時健康量測推播，持之以恆紀錄可激發完美身型動能體魄！",
            "save_settings_btn" to "儲存設定",
            "save_success_toast" to "✅ 個人健康設定存擋完成！已同步轉換目前數據。",
            "enter_valid_height" to "請填寫合規身高資料！",
            "enter_valid_target_weight" to "請填寫合規體重目標！",
            "onboarding_title" to "✨ 歡迎使用 BMI 助理 ✨",
            "onboarding_subtitle" to "在您第一次進入前，請先填寫以下您的基本健康資訊，我們將為您量身打造最佳的 BMI 指標追蹤！",
            "onboarding_gender" to "生理性別",
            "onboarding_age" to "您的年齡",
            "onboarding_weight" to "目前體重",
            "onboarding_submit" to "開啟我的健康完美體態之旅",
            "gender_male" to "男",
            "gender_female" to "女",
            "gender_other" to "其他",
            "lang_setting_title" to "🌐 語言",
            "lang_setting_desc" to "請點選您所期望的介面語言設定",
            "zh_tw" to "繁體中文",
            "en_us" to "English (USA)",
            // Dashboard translations
            "current_bmi" to "您的目前 BMI",
            "latest_measure" to "最新量測體重",
            "bmi_normal" to "正常",
            "bmi_underweight" to "過輕",
            "bmi_overweight" to "過重",
            "bmi_obese" to "肥胖",
            "days_tracked" to "已持續記錄",
            "days_unit" to "天",
            "latest_time" to "最新記錄時間",
            "weight_trend_title" to "📈 體重波動與 BMI 區間曲線",
            "ai_coach" to "🤖 Gemini 智慧健康教練",
            "ai_coach_tip" to "結合您的歷史體重趨勢與個人資訊，由 Gemini 提供個性化的健康指引與建議。",
            "btn_generate_ai" to "生成 AI 健康分析報告 🔮",
            "weight_log_title" to "⚖️ 記錄體重",
            "weight_log_field" to "輸入目前體重",
            "weight_note_field" to "今日摘要",
            "add_record_btn" to "新增今日量測數據",
            "success_log" to "✅ 體重記錄成功歸檔！",
            "please_enter_weight" to "請輸入合規體重數據！",
            // Newly added for deeper translation completeness
            "welcome_back" to "歡迎回來 ✨",
            "today_health_status" to "今日健康狀態",
            "body_status_gauge" to "目前身體狀況量表",
            "unrecorded" to "尚未記錄",
            "current_height" to "目前身高",
            "update_time" to "更新時間",
            "health_goal_progress" to "健康目標進程",
            "difference_above_target" to "距離理想目標還差 **%s** %s！持之以恆必有所獲。",
            "difference_below_target" to "已超越目標 **%s** %s！太棒了，請繼續維持精實體態！",
            "difference_equal_target" to "正好達成目標防線！完美持平，為自己的健康點個讚吧！",
            "one_sec_shortcut" to "⚡ 1 秒智能快捷記錄",
            "shortcut_desc" to "自動以昨天的紀錄 %s %s 微調，免除重填負擔：",
            "same_as_yesterday" to "同昨日體重：%s %s 快速加載",
            "ai_coach_title" to "Gemini AI 雲端健康教練",
            "ai_loading_message" to "正在解算您的歷史 BMI 數據並聯繫 Gemini AI...",
            "ai_error_prefix" to "連線失敗：",
            "retry" to "重試",
            "dialog_record_title" to "✍️ 記錄今日身體指標",
            "dialog_prefilled_desc" to "已為您自動載入上一次的身高 (%s %s) 及體重紀錄，僅需微調！",
            "dialog_weight_label" to "體重",
            "dialog_date_label" to "量測日期：今天 (%s)",
            "dialog_save_btn" to "儲存紀錄",
            "delete_record_tooltip" to "刪除記錄",
            "delete_confirm_detail" to "您即將刪除於 %s 量測的 %s %s 體重紀錄。此動作將無法復原。",
            "chart_week" to "本週",
            "chart_month" to "本月",
            "chart_year" to "今年",
            "chart_target" to "目標",
            "chart_empty_title" to "此時段內尚無量測紀錄",
            "chart_empty_desc" to "開始由捷徑或右上方 ＋ 號記錄您今日的體重！",
            "developer_mode_title" to "🧪 開發者模式",
            "developer_mode_desc" to "提供進階調試與測試開發工具。",
            "initial_intro_btn" to "▶️ 重新進入初始功能介紹（Onboarding）",
            "random_data_btn" to "🎲 自動模擬生成 30 天合理體重數據，每天一筆 (30 筆)",
            "random_data_success" to "✅ 已成功模擬並生成 30 筆合理的歷史體重記錄！",
            "day_mon" to "一",
            "day_tue" to "二",
            "day_wed" to "三",
            "day_thu" to "四",
            "day_fri" to "五",
            "day_sat" to "六",
            "day_sun" to "日",
            "chart_view_settings" to "📊 圖表與檢視設定",
            "week_start_label" to "每週開始日",
            "date_format_label" to "年月日顯示方式",
            "week_monday" to "星期一",
            "week_sunday" to "星期日",
            "format_default" to "預設 (語系化)"
        )

        val en = mapOf(
            "app_title" to "🧘 BMI Assistant",
            "app_title_dashboard" to "🧘 BMI Assistant",
            "app_title_history" to "📊 Weight Trend History",
            "app_title_settings" to "⚙️ Settings & Alarm",
            "home" to "Dashboard",
            "history" to "History",
            "settings" to "Settings",
            "trending_and_stats" to "Trend & Statistics",
            "history_track" to "Measurement Records",
            "export_report" to "Export Report",
            "all_history" to "All History Logs",
            "add_record" to "Add Record",
            "duplicate_record_title" to "⚠️ Duplicate Record",
            "duplicate_record_desc" to "A record already exists for this date. Would you like to overwrite it?",
            "overwrite_btn" to "Overwrite",
            "no_history" to "📌 No data logged yet",
            "no_history_desc" to "Click the ' + ' sign on top of the dashboard to easily write your weight logs, keep in shape!",
            "delete_confirm_title" to "⚠️ Confirm deletion?",
            "delete_confirm_desc" to "You are about to delete this weight log. This action is permanent.",
            "delete_confirm_btn" to "OK, Delete",
            "cancel" to "Cancel",
            "metric_system" to "📐 Metric / Imperial Unit System",
            "metric_system_desc" to "Set weight and height systems, historical data converts automatically",
            "metric_opt" to "Metric (kg / cm)",
            "imperial_opt" to "Imperial (lb / in)",
            "physical_metrics" to "👤 Basic Body Metrics",
            "target_goals_title" to "🎯 Weight & BMI Goal",
            "target_goals_desc" to "Configure your target weight, and we will calculate your projected goal BMI in real-time.",
            "target_bmi_label" to "Projected Goal BMI:",
            "recommended_standard_weight" to "Recommended standard weight (BMI 22.0):",
            "height_label" to "Height",
            "target_weight_label" to "Weight",
            "reminder_title" to "⏰ Daily & Repeating Reminders",
            "reminder_desc" to "Scheduled alarms to help you never forget recording",
            "reminder_hour" to "Hour",
            "reminder_min" to "Minute",
            "reminder_freq" to "Alarm Frequency",
            "reminder_inactive_desc" to "💡 Reminder is inactive. Suggest turning it on to receive prompt push notifications!",
            "save_settings_btn" to "Save & Sync Historical Logs",
            "save_success_toast" to "✅ Settings saved successfully! Converted all records.",
            "enter_valid_height" to "Please enter valid height!",
            "enter_valid_target_weight" to "Please enter valid target weight!",
            "onboarding_title" to "✨ Welcome to BMI Assistant ✨",
            "onboarding_subtitle" to "To get started, please fill in your basic health info below. We will customize your custom tracking tracker!",
            "onboarding_gender" to "Biological Gender",
            "onboarding_age" to "Age",
            "onboarding_weight" to "Current Weight",
            "onboarding_submit" to "Start My Healthy Journey",
            "gender_male" to "Male",
            "gender_female" to "Female",
            "gender_other" to "Other",
            "lang_setting_title" to "🌐 Interface Locale / Language Settings",
            "lang_setting_desc" to "Select your preferred application language",
            "zh_tw" to "繁體中文",
            "en_us" to "English (USA)",
            // Dashboard translations
            "current_bmi" to "Current BMI",
            "latest_measure" to "Latest Weight Log",
            "bmi_normal" to "Normal",
            "bmi_underweight" to "Underweight",
            "bmi_overweight" to "Overweight",
            "bmi_obese" to "Obese",
            "days_tracked" to "Continuous Tracking",
            "days_unit" to "Days",
            "latest_time" to "Latest record time",
            "weight_trend_title" to "📈 Weight Trend & BMI Zones",
            "ai_coach" to "🤖 Gemini Health Coach",
            "ai_coach_tip" to "Leveraging your weight trends and background info, Gemini compiles a personalized health report.",
            "btn_generate_ai" to "Generate AI Health Report 🔮",
            "weight_log_title" to "⚖️ Record Weight Log",
            "weight_log_field" to "Enter weight",
            "weight_note_field" to "Today's Summary",
            "add_record_btn" to "Log Current Weight",
            "success_log" to "✅ Weight logged successfully!",
            "please_enter_weight" to "Please input valid weight data!",
            // Newly added for deeper translation completeness
            "welcome_back" to "Welcome Back ✨",
            "today_health_status" to "Today's Health Status",
            "body_status_gauge" to "Current Body Status Gauge",
            "unrecorded" to "Unrecorded",
            "current_height" to "Current Height",
            "update_time" to "Last Updated",
            "health_goal_progress" to "Body & Goal Progress",
            "difference_above_target" to "**%s** %s away from your ideal target! Consistency is key.",
            "difference_below_target" to "Superb! Exceeded target by **%s** %s! Keep up the great health!",
            "difference_equal_target" to "Target accomplished! Perfectly on track, keep maintaining the form!",
            "one_sec_shortcut" to "⚡ 1-Sec Smart Shortcuts",
            "shortcut_desc" to "Tweak based on yesterday's log (%s %s) without typing:",
            "same_as_yesterday" to "Same as yesterday: %s %s Express Log",
            "ai_coach_title" to "Gemini AI Smart Health Coach",
            "ai_loading_message" to "Analyzing historical BMI data and reaching out to Gemini AI...",
            "ai_error_prefix" to "Connection failed: ",
            "retry" to "Retry",
            "dialog_record_title" to "✍️ Record Daily Health Metrics",
            "dialog_prefilled_desc" to "Auto-loaded your last height (%s %s) and weight, just tweak to save!",
            "dialog_weight_label" to "Weight",
            "dialog_date_label" to "Date: Today (%s)",
            "dialog_save_btn" to "Save Record",
            "delete_record_tooltip" to "Delete record",
            "delete_confirm_detail" to "You are about to delete the weight record of %s %s logged on %s. This action cannot be undone.",
            "chart_week" to "Week",
            "chart_month" to "Month",
            "chart_year" to "Year",
            "chart_target" to "Target",
            "chart_empty_title" to "No records in this period",
            "chart_empty_desc" to "Record your weight now using shortcuts or '+'!",
            "developer_mode_title" to "🧪 Developer Mode",
            "developer_mode_desc" to "Provides advanced collection of debugging and testing tools.",
            "initial_intro_btn" to "▶️ Replay Initial Introduction (Onboarding)",
            "random_data_btn" to "🎲 Generate 30-Day Reasonable Weight Logs, One Log Per Day (30 logs)",
            "random_data_success" to "✅ Simulated & generated 30 realistic historical weight logs!",
            "day_mon" to "Mon",
            "day_tue" to "Tue",
            "day_wed" to "Wed",
            "day_thu" to "Thu",
            "day_fri" to "Fri",
            "day_sat" to "Sat",
            "day_sun" to "Sun",
            "chart_view_settings" to "📊 Chart & View Settings",
            "week_start_label" to "Week Start Day",
            "date_format_label" to "Date Presentation Format",
            "week_monday" to "Monday",
            "week_sunday" to "Sunday",
            "format_default" to "Default (System)"
        )

        val dict = if (lang.startsWith("en", ignoreCase = true)) en else tw
        return dict[key] ?: key
    }
}
